### ISSUE TITLE
Zero Health Bug

### ISSUE THREAD

**Issue by Catallaxis7** [kinggath/Workshop-Plus#27]
Conflict between WS+ flight mode and health suppression effect that rads have in CC Survival mode.

If the player has rads in Survival mode and enters Workshop mode with flight enabled, and if a health regen effect is active or a level up occurs whike in workshop mode, the player will lose health.

If health falls to zero before exiting workshop mode, it will remain stuck at zero after exiting but the player will not immediately die. Any subsequent attempt to heal, besides the heal effect from leveling up, will result in an instant death.

**Comment by kinggath** [comment]
In next patch (1.0.12), rads will now be cleared before Flight mode is enabled. Uncertain if this will fix the issue as I can't replicate it.

**Comment by Unknown-Zombie** [comment]
This honestly feels too cheaty the way it is now.

Is there another way to do this? Could the mod fetch the character's rads actorvalue before curing them, store it in a variable, and reapply those rads upon exiting workshop mode?

**Comment by kinggath** [comment]
Workshop Plus is always going to be cheaty, but each feature can be disabled. If you disable flight mode, the rad cleaning won't occur.

**Comment by Unknown-Zombie** [comment]
For what it's worth, this did resolve the bug.

WS+ 1.0.11:
[https://youtu.be/q4TamEmXJv8](url)

WS+ 1.0.12:
[https://youtu.be/ljfyOePSs7Q](url)

In both videos, actions taken were the same:
1. Be in survival mode.
2. Have rads.
3. Use stimpack to gain a heal-over-time effect.
4. Open workshop with flight mode active.
5. Close workshop.
6. Open Pip-Boy (or attempt to).
