### ISSUE TITLE
Tracking and fallowers

### ISSUE THREAD

**Issue by Smockwal** [kinggath/Workshop-Plus#38]
When recruiting a follower assigned to a settlement, if they have the tracking function activate on them, the quest stays active and there is no wait to stop it as long as you don't re-assign that follower to the same settlement.t.

How to:
-Recruit any follower.
-Dismiss it and send them to a settlement.
-In that settlement, look at the follower and activate tracking function.
-Ask that follower to follow you.

The tracking quest stays active and there is no way to turn it off (off from your quest list)

**Comment by kinggath** [comment]
Should be fixed for next build.
